# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df914bf332b9bf5d4f4213f09c28542f4bf4dd6fbcc5b35c0304e1aa0745185cb0a2f2ad4a3b99cd04097c70296670efc4c2a4f431b9a0642f870279de55ee73

test:
  secret_key_base: 9d0c756050d0bb7ccd34ad9e5463f7f140c4cb47d829537140a738a6a62dd6cd8aaf9a5f17e886d536654dd18e6d05384d6dd9c74ae4fbbdd2b1699cd6a74ae8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
